### ISSUE TITLE
2425-W-008 Festival dump and modelling

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-planet-lavitrine#44]
Work Order https://docs.google.com/document/d/1awbPG-iqOabuvBm8-Gr-zkm4dF0qWAEZqJHCC2fiS_Y/edit

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-lavitrine/issues/45
- [ ] https://github.com/culturecreates/artsdata-planet-lavitrine/issues/30
- [ ] Add controlled vocabulary ad:FestivalSeries
- [ ] Mint festival events so they are part of the Artsdata core graph
- [ ] Add process to link ad:Festival and ad:FestivalSeries using Wikidata
- [ ] Dump of Festivals from Artsdata core graph to include ad:FestivalSeries
```
